### ISSUE TITLE
How is day counted?

### ISSUE THREAD

**Issue by Krosta8** [SkyFire55/daily-rewards#6]
Hello,
I have a question about the days.
When I take reward at 1:00 pm, next day I can take reward at 1:00pm or at 0:01 am next day?

Reason why am I asking..
I want to have the rewards exactly from 0:00am available. 
One day I take reward at 1:00pm and next day I can take it in the first minute of the day.

Is this possible?

**Comment by VimbaTheFish** [comment]
Yep. It works very easy - it starts from moment, your time.conf file was generated, and then lasts every 24 hours. If you want to change this time, you can just use command /dr clear in that time which you want to make a time of startpoint. So, if you use this command at 1:53, so new rewards will be avaliable every 24 hours since 1:53.

If I answered your question, close this issue, please. If no - I'm ready to answer.
